worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  192.168.1.100;

        # Directorio de los archivos compilados
        root   /usr/share/nginx/html;
        index  index.html;

        # Cabeceras de seguridad básicas
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        # 1. Servir los archivos estáticos de la app React
        location / {
            try_files $uri $uri/ /index.html;
        }

        # 2. Proxy para API de Restream
        location /api/restream/ {
            proxy_pass https://player-backend.restream.io/;
            proxy_ssl_server_name on;
            proxy_set_header Host player-backend.restream.io;
            proxy_set_header Origin https://player.restream.io;
            proxy_set_header Referer https://player.restream.io/;
            proxy_set_header Accept-Encoding "";
        }

        # 3. Proxy para Cloudflare Stream
        location /api/cloudflare/ {
            proxy_pass https://customer-gllhkkbamkskdl1p.cloudflarestream.com/;
            proxy_ssl_server_name on;
            proxy_set_header Host customer-gllhkkbamkskdl1p.cloudflarestream.com;
            proxy_set_header Accept-Encoding "";
        }

        # 4. Proxy para API de Telefe
        location /api/mitelefe/ {
            proxy_pass https://santafe.mitelefe.com/;
            proxy_ssl_server_name on;
            proxy_set_header Host santafe.mitelefe.com;
            proxy_set_header Origin https://santafe.mitelefe.com;
            proxy_set_header Referer https://santafe.mitelefe.com/;
        }

        # 5. Proxy para video de Telefe Akamai
        location /api/telefe-akamai/ {
            proxy_pass https://telefecanal1.akamaized.net/;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
            
            proxy_set_header Origin "https://santafe.mitelefe.com";
            proxy_set_header Referer "https://santafe.mitelefe.com/";
            proxy_set_header Accept-Encoding "";
            
            # Permitimos que la entrada sea desde cualquier origen local para evitar problemas con la TV
            proxy_hide_header Access-Control-Allow-Origin;
            add_header Access-Control-Allow-Origin * always;
        }
    }
}
