worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    server {
        listen 80;
        # Escucha en el puerto 80 para acceso local simple
        server_name _; 

        root   /usr/share/nginx/html;
        index  index.html;

        # Cabeceras para permitir que la TV acceda al contenido
        add_header Access-Control-Allow-Origin * always;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxies (Igual que antes para saltar el CORS de los canales)
        location /api/restream/ {
            proxy_pass https://player-backend.restream.io/;
            proxy_set_header Host player-backend.restream.io;
            proxy_set_header Origin https://player.restream.io;
        }

        location /api/cloudflare/ {
            proxy_pass https://customer-gllhkkbamkskdl1p.cloudflarestream.com/;
        }

        location /api/mitelefe/ {
            proxy_pass https://santafe.mitelefe.com/;
        }

        location /api/telefe-akamai/ {
            proxy_pass https://telefecanal1.akamaized.net/;
            add_header Access-Control-Allow-Origin * always;
        }
    }
}
